---
settings:
  name: BlueXP replication
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXP Replizierungsdokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr zur BlueXP Replizierung
      url: "/concept-replication.html"
    - title: Richten Sie die Datenreplizierung ein
      url: "/task-replicating-data.html"
  - title: Management der Datenreplizierung
    url: "/task-managing-replication.html"
  - title: Weitere Informationen .
    entries:
    - title: Weitere Informationen zu Replizierungsrichtlinien
      url: "/concept-replication-policies.html"
    - title: Weitere Informationen zu Backup-Richtlinien
      url: "/concept-backup-policies.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
